name: "yaml-schema-checker"
description: "A Github action for checking .yaml files using JSON schemas"
branding:
  icon: "check-square"
  color: "blue"
inputs:
  jsonSchemaFile:
    description: "jsonSchemaFile"
    required: true
  yamlFiles:
    description: "yamlFiles"
    required: true
outputs:
  validFiles:
    description: Comma separated list of files that passed
  invalidFiles:
    description: Comma separated list of files that failed
runs:
  using: "node16"
  main: "dist/index.js"
